### ISSUE TITLE
HandleFunc called Twice

### ISSUE THREAD

**Issue by eloyekunle** [gophercises/quiet_hn#3]
Great work on this, Jon.
Quick one, http requests from the browser are making two requests, one for the page itself and another for the favicon. [This discussion](https://stackoverflow.com/questions/33432192/handlefunc-being-called-twice) on SO shows that it happens when the HTML file doesn't specify a favicon.
I think we can fix this by adding a shortcut link to the HTML.

**Comment by joncalhoun** [comment]
You are welcome to add this into your own solution, but I won't be adding it to this exercise as I feel it distracts from the main learning points and just makes things a little more complex than necessary. I do appreciate you pointing it out and doing some additional research into it :)

PS - Sorry this response is so delayed :(

**Comment by eloyekunle** [comment]
Oh okay.
